services:
  - type: web
    name: jarvis-md
    env: docker
    branch: main
    repo: https://github.com/dontechinc/GHOST_DL-BOT-md/.git
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
